apiVersion: v1
kind: ConfigMap
metadata:
  name: shiny
data:
{{- $values := pick .Values "proxy" "logging" }}
{{- $_ := set $values "proxy" (omit $values.proxy "image" "annotations" "labels" "nodeSelector" "resources" "service") }}
{{- range .Values.proxy.specs }}
  {{- if not (index . "container-memory-request") }}
    {{- $_ := set . "container-memory-request" $.Values.appPod.resources.requests.memory }}
  {{- end }}
  {{- if not (index . "container-cpu-request") }}
    {{- $_ := set . "container-cpu-request" $.Values.appPod.resources.requests.cpu }}
  {{- end }}
  {{- if not (index . "container-memory-limit") }}
    {{- $_ := set . "container-memory-limit" $.Values.appPod.resources.limits.memory }}
  {{- end }}
  {{- if not (index . "container-cpu-limit") }}
    {{- $_ := set . "container-cpu-limit" $.Values.appPod.resources.limits.cpu }}
  {{- end }}
{{- end }}
  application.yml: |
  {{- $values | toYaml | nindent 4 }}
