apiVersion: v1
kind: ServiceAccount
metadata:
  name: shiny
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shiny
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shiny
subjects:
  - kind: ServiceAccount
    name: shiny
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: shiny
