kind: Secret
apiVersion: v1
metadata:
  name: shiny
type: Opaque
data:
{{- $values := pick .Values "proxy" }}
{{- $_ := set $values "proxy" (pick $values.proxy "ldap" "kerberos" "keycloak" "openid" "saml" "social" "users") }}
  secrets.json: {{ $values | toJson | b64enc | quote }}
