apiVersion: v1
kind: Service
metadata:
  name: shiny
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: shiny
  ports:
    - port: 8080
      targetPort: 8080
      {{- if .Values.proxy.service.ports.nodePort }}
      nodePort: {{ .Values.proxy.service.ports.nodePort }}
      {{- end }}

